# Generated by Django 5.2.18 on 2026-10-07 15:47

import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.common.validators.validate_non_negative_decimal])),
                ('currency', models.CharField(max_length=3)),
                ('unit', models.CharField(max_length=32)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='materials.material')),
            ],
            options={
                'ordering': ('-effective_from', 'material__name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='material_price_valid_date_range')],
            },
        ),
    ]
