# Generated by Django 5.2.18 on 2026-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('plywood', 'Plywood'), ('mdf', 'MDF'), ('blockboard', 'Blockboard'), ('particle_board', 'Particle Board'), ('laminate', 'Laminate'), ('veneer', 'Veneer'), ('edge_band', 'Edge Band'), ('hardware', 'Hardware')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'name'),
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='unique_material_name_per_category')],
            },
        ),
    ]
