# Generated by Django 5.2.18 on 2026-10-07 15:47

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_width_mm', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.common.validators.validate_positive_decimal])),
                ('sheet_height_mm', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.common.validators.validate_positive_decimal])),
                ('kerf_mm', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[apps.common.validators.validate_non_negative_decimal])),
                ('parts', models.JSONField(default=list)),
                ('layout', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
